services:
  - type: web
    name: robot-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn trigger:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: database
          name: robot-db
          property: connectionString
